// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Contact Us"
          text="Need help or have questions? Our support team is ready to assist you at any time."
          primaryButton={{
            text: "Contact Support",        href: "#"}}
          secondaryButton={{
            text: "FAQs",        href: "#faq"}}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
