// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="Help Center"
          title="Frequently Asked Questions"
          description="Find answers to common questions about our platform and services."
          categories={[
            {
              name: "Purchases",          items: [
                {
                  question: "Can I return a book?",              answer: "All digital purchases are final."},
                {
                  question: "What formats are supported?",              answer: "We support ePub and PDF formats."},
              ],
            },
            {
              name: "Account",          items: [
                {
                  question: "How to delete my account?",              answer: "Contact support via our contact page."},
                {
                  question: "Is my payment data secure?",              answer: "Yes, we use industry-standard encryption."},
              ],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
