// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitMediaGrid from '@/components/sections/hero/HeroSplitMediaGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplitMediaGrid
        tag="eBook Bazaar"
        title="Discover, Read and Download the Best eBooks"
        description="Thousands of eBooks across business, self-help, education, technology and fiction."
        primaryButton={{"href":"#book-store","text":"Browse Books"}}
        secondaryButton={{"href":"#categories","text":"Explore Categories"}}
        items={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/professional-young-woman-holding-mobile-phone_23-2148452658.jpg"},
            {
              imageSrc: "http://img.b2bpic.net/free-photo/beautiful-landscape-from-magazine-coming-life_23-2151158560.jpg"},
          ]}
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}
