// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitMediaGrid from '@/components/sections/hero/HeroSplitMediaGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplitMediaGrid
          tag="Your Digital Library"
          title="Unlock Infinite Stories with BookVerse"
          description="Discover thousands of eBooks across all genres. Read anytime, anywhere with our instant download platform."
          primaryButton={{
            text: "Browse Books",        href: "#products"}}
          secondaryButton={{
            text: "Explore Categories",        href: "#"}}
          items={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/professional-young-woman-holding-mobile-phone_23-2148452658.jpg"},
            {
              imageSrc: "http://img.b2bpic.net/free-photo/beautiful-landscape-from-magazine-coming-life_23-2151158560.jpg"},
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
