// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsFeatureCards from '@/components/sections/metrics/MetricsFeatureCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsFeatureCards
          tag="Our Growth"
          title="BookVerse by the Numbers"
          description="Connecting millions of readers with the authors they love."
          metrics={[
            {
              value: "1.2M+",          title: "Books Available",          features: [
                "Instant Download",            "ePub/PDF Support"],
            },
            {
              value: "500K+",          title: "Active Readers",          features: [
                "Community Reviews",            "Personalized Recs"],
            },
            {
              value: "10K+",          title: "Authors Trusted",          features: [
                "Easy Publishing",            "Global Reach"],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
