// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "products" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProductsSection(): React.JSX.Element {
  return (
    <div id="products" data-section="products">
        <SectionErrorBoundary name="products">
              <FeaturesImageBento
          tag="Curated Picks"
          title="Explore Our Collections"
          description="Hand-picked categories to help you find your next favorite read."
          items={[
            {
              title: "Fiction",          description: "Engaging stories and epic novels.",          imageSrc: "http://img.b2bpic.net/free-photo/close-up-woman-reading-mock-up-magazine_23-2148295563.jpg"},
            {
              title: "Business",          description: "Master your professional journey.",          imageSrc: "http://img.b2bpic.net/free-photo/stack-clean-white-papers-office-business-use_187299-48025.jpg"},
            {
              title: "Technology",          description: "Stay ahead of the curve.",          imageSrc: "http://img.b2bpic.net/free-photo/square-book-office-mockup_23-2151731936.jpg"},
            {
              title: "Education",          description: "Empower your mind today.",          imageSrc: "http://img.b2bpic.net/free-photo/gradient-technology-background_23-2151895866.jpg"},
            {
              title: "Self-Help",          description: "Improve your daily lifestyle.",          imageSrc: "http://img.b2bpic.net/free-photo/physical-paper-book-background-closeup_58702-6903.jpg"},
            {
              title: "Kids Books",          description: "Fun adventures for everyone.",          imageSrc: "http://img.b2bpic.net/free-photo/close-up-stack-books_1098-1352.jpg"},
            {
              title: "Best Sellers",          description: "What everyone is reading.",          imageSrc: "http://img.b2bpic.net/free-photo/close-up-pastor-praying-with-bible_23-2149300856.jpg"},
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
