// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonial" section.

import React from 'react';
import TestimonialTrustCard from '@/components/sections/testimonial/TestimonialTrustCard';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialSection(): React.JSX.Element {
  return (
    <div id="testimonial" data-section="testimonial">
        <SectionErrorBoundary name="testimonial">
              <TestimonialTrustCard
          quote="BookVerse has completely changed the way I buy my books. The instant access and clean interface are unparalleled in the market today."
          rating={5}
          author="Sarah Johnson, Passionate Reader"
          avatars={[
            {
              name: "Alice Smith",          imageSrc: "http://img.b2bpic.net/free-photo/close-up-notepad-with-list-text-milk_23-2148123811.jpg"},
            {
              name: "Bob Jones",          imageSrc: "http://img.b2bpic.net/free-vector/geometric-gradient-shapes-covers-dark-background_23-2148446045.jpg"},
            {
              name: "Carol White",          imageSrc: "http://img.b2bpic.net/free-photo/digital-art-style-illustration-mental-health-day-awareness_23-2151813240.jpg"},
            {
              name: "David Brown",          imageSrc: "http://img.b2bpic.net/free-photo/3d-character-emerging-from-smartphone_23-2151336532.jpg"},
            {
              name: "Eva Green",          imageSrc: "http://img.b2bpic.net/free-photo/african-american-man-elegant-suit-holds-black-hat-isolated-dark-background_613910-6600.jpg"},
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
